/*
We have an e-commerce database, and we need to write a stored procedure that retrieves 
the sales of cities and categories on a monthly basis. 
Then, transfer the result of this stored procedure into a temporary table and display the sales of the food category 
with cities as rows and months as columns.
*/
CREATE PROC SPSALESBY_CITY_MONTH
AS
select C.CITY,I.CATEGORY1,DATEPART(MONTH,O.DATE_) MONTHNR
,DATENAME(MONTH,O.DATE_)MONTHNAME, SUM(OD.LINETOTAL)TOTALSALE  from ORDERS O
JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
JOIN ADDRESS A ON O.ADDRESSID=A.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN CITIES C ON A.CITYID=C.ID
GROUP BY C.CITY,I.CATEGORY1,DATEPART(MONTH,O.DATE_) ,
DATENAME(MONTH,O.DATE_) 
ORDER BY C.CITY,I.CATEGORY1,DATEPART(MONTH,O.DATE_) 

CREATE TABLE #T(CITY VARCHAR(50), CATEGORY1 VARCHAR(50), MONTHNR INT, MONTHNAME VARCHAR(20), TOTALSALE FLOAT)

INSERT INTO #T
EXEC SPSALESBY_CITY_MONTH

SELECT * FROM #T

SELECT DISTINCT CITY,CATEGORY1,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=1 AND CITY=T.CITY) JANUARY,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=2 AND CITY=T.CITY) FEBRUARY,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=3 AND CITY=T.CITY) MARCH,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=4 AND CITY=T.CITY) APRIL,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=5 AND CITY=T.CITY) MAY,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=6 AND CITY=T.CITY) JUNE,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=7 AND CITY=T.CITY) JULY,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=8 AND CITY=T.CITY) AUGUST,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=9 AND CITY=T.CITY) SEPTEMBER,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=10 AND CITY=T.CITY) OCTOBER,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=11 AND CITY=T.CITY) NOVEMBER,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND MONTHNR=12 AND CITY=T.CITY) DECEMBER
FROM #T T
WHERE CATEGORY1 = 'GIDA'

DROP TABLE #T 
