/*We have a table where users are stored, and we need to write a stored procedure that will take the username,
email address, password, and IP information for login processes. 
The procedure will also automatically record the login activities. */

CREATE PROC SPLOG
@USERNAME AS VARCHAR(50)= '',
@EMAIL AS VARCHAR(100)='',
@PASSWORD AS VARCHAR(100),
@IPADDRESS AS VARCHAR(20)

AS
DECLARE @LOGINTYPE AS INT
DECLARE @USERID AS INT
IF @USERNAME <> ''
BEGIN
	SELECT @USERID = ID FROM USERS WHERE USERNAME_ = @USERNAME AND PASSWORD_ = @PASSWORD
	IF @USERID IS NOT NULL
	BEGIN
		SET @LOGINTYPE = 1
	END
	ELSE
	BEGIN
		SET @LOGINTYPE = 0
	END
	INSERT INTO USERLOGIN_LOG (USERID, USERNAME, LOGINTYPE, IPADDRESS, DATE_)
	VALUES (@USERID, @USERNAME,@LOGINTYPE,@IPADDRESS,GETDATE())
END

IF @EMAIL <> ''
BEGIN
	SELECT @USERID = ID FROM USERS WHERE EMAIL = @EMAIL AND PASSWORD_ = @PASSWORD
	IF @USERID IS NOT NULL
	BEGIN
		SET @LOGINTYPE = 1
	END
	ELSE
	BEGIN
		SET @LOGINTYPE = 0
	END
	INSERT INTO USERLOGIN_LOG (USERID, USERNAME, LOGINTYPE, IPADDRESS, DATE_)
	VALUES (@USERID, @EMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())
END

SELECT @LOGINTYPE LOGINTYPE




EXEC SPLOG @USERNAME = 'A_POCAN',
@PASSWORD = 'B7D7C19FD6334E5C9B227F4F585276CF',
@IPADDRESS = '127.10.2'
